# Generated by Django 5.2.2 on 2025-07-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('snippet', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('fetched_on', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('nb_visit', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
